//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class pie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pie()
        {
            ////this class is unused now . it was part of the previous attemps 
            this.ShoppingCartItem = new HashSet<ShoppingCartItem>();
        }
    
        public int Id { get; set; }
        [Required]
        public string name { get; set; }
        public string details { get; set; }
        public string imageurl { get; set; }
        public int catid { get; set; }

       [Required]
        public int prce { get; set; }
        [NotMapped]
        public HttpPostedFileBase upload { get; set; }


        public virtual category category { get; set; }
        ////this  is unused now . it was part of the previous attemps 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        ////this class is unused now . it was part of the previous attemps 
        public virtual ICollection<ShoppingCartItem> ShoppingCartItem { get; set; }
    }
}
